### ISSUE TITLE
Convert event descriptions in bills from prose to keywords

### ISSUE THREAD

**Issue by wfdd** [openpatata/openpatata-data#3]
In order to reduce translator load and improve categorisation, I propose that the descriptions of items in the `events` list, which chronicles the actions Parliament takes on a bill, be changed to use predefined keywords. The keyword would be placed in a new field, `action`, and the `description` field would be removed. Accordingly, the list would be renamed `actions`. Each keyword might be potentially associated with additional fields, e.g. `submit` would require `by` (a list of sponsors). As a starting point, the following should be implemented:

```yaml
...
action: submit
by:
- name: %str
  note: %str
```
```yaml
...
action: resubmit
```
```yaml
...
action: postpone
what: second reading|third reading
```
```yaml
...
action: vote
on: third reading|veto override
breakdown:
- name: %str
  option: yes|no|abstain
counts:
- count: %int
  option: yes|no|abstain
motion: %str
remarks: %literal
result: pass|fail
```
```yaml
...
action: other
description:
  el: %str
  en: %str
```
